<Project Sdk="Microsoft.NET.Sdk">
    
    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
            <!--        <PrivateAssets>all</PrivateAssets>--> <!-- Comment this out to apply migrations -->
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\EquipLease.Application\EquipLease.Application.csproj"/>
    </ItemGroup>

</Project>
